### ISSUE TITLE
problems when extracting features

### ISSUE THREAD

**Issue by univerone** [ddofer/asap#3]
I'm following "Getting-Started:-A-Basic-Tutorial" and after exec
`extract_windows_from_file(annotated_seqs_file, extract_annotations = True, csv_output_file = csv_output_file, window_extraction_params = window_extraction_params)`, 
then I got a rather small csv file in serveral minutes ,containing 68807 windows, each having about 200 features.
But in this document ,it mentions that 
> containing 68807 windows, each having 735 features.

i don't know what's wrong with this(if posiible,can i have a look at the correct feature file?)

**Comment by nadavbra** [comment]
Hi,

Can you provide us with a full .py code file replicating this problem?
Please also specify what version of Python an related libraries you use.

Nadav

**Comment by univerone** [comment]
> Hi,
> 
> Can you provide us with a full .py code file replicating this problem?
> Please also specify what version of Python an related libraries you use.
> 
> Nadav

Thanks for your kindness, I'm sorry that I'm rather unfamiliar with github at that time, so I didn't get your message and respond in time.
